Add "supported" property
abdonrd/device-orientation pull request #5
Opened 2017-06-15 13:11 UTC by FluorescentHallucinogen

2017-06-15 23:51 UTC, abdonrd requested changes
Good job! 😄

2017-06-15 23:51 UTC, abdonrd commented on device-orientation.html
> +          value: false,
Please, remove the default value.
If the browser supports the Device Orientation API, we should never show `false`.

2017-06-16 05:58 UTC, FluorescentHallucinogen commented on device-orientation.html
> +          value: false,
Done.

2017-06-16 06:13 UTC, FluorescentHallucinogen commented
I've renamed "supported" property to "api-supported".

2017-06-16 07:36 UTC, FluorescentHallucinogen commented
@abdonrd I've removed `value: false` from the code. Is Polymer property default value optional? Shouldn't I use `value: ''` instead of removing it?

2017-06-16 07:47 UTC, FluorescentHallucinogen commented
@abdonrd Or should I use `value: null`?

2017-06-16 08:38 UTC, abdonrd commented
@FluorescentHallucinogen yes, the default value is optional.

2017-06-16 08:41 UTC, abdonrd commented
We should add the new property to the demo & inline-demo (README.md).

2017-06-16 08:43 UTC, FluorescentHallucinogen commented
I'll do it right now. )

2017-06-16 08:52 UTC, FluorescentHallucinogen commented
Done. ;)

2017-06-16 08:58 UTC, abdonrd approved these changes

2017-06-16 08:59 UTC, abdonrd commented
Thanks @FluorescentHallucinogen! 👏

2017-06-16 09:04 UTC, merged

2017-06-16 09:05 UTC, FluorescentHallucinogen commented
I think we should increment MINOR in MAJOR.MINOR.PATCH semantic version, bacause new functionality added in a backwards-compatible manner.

2017-06-16 09:11 UTC, abdonrd commented
@FluorescentHallucinogen I'm thinking in first add #7.

2017-06-16 10:39 UTC, abdonrd commented
@FluorescentHallucinogen done! https://github.com/abdonrd/device-orientation/releases/tag/v0.3.0

2017-06-16 10:43 UTC, FluorescentHallucinogen commented
@abdonrd 
> done! device-orientation v0.3.0

Oh, I think `sensors-available` property should be added to the demo (`demo/index.html`) and inline-demo (`README.md`) too.

2017-06-16 10:44 UTC, FluorescentHallucinogen commented
I'll add it now. ;)

2017-06-16 10:47 UTC, abdonrd commented
It's already there. 😕

2017-06-16 10:50 UTC, FluorescentHallucinogen commented
Oh, sorry, you are right. Good job! 😉